### ISSUE TITLE
Add Configurable Kits

### ISSUE THREAD

**Issue by Soham52** [John-Paul-R/kits#1]
The following commands can be added to add kits-
1./kit create- creates a kit with the player's current inventory (only for admins)
2./kits - shows list of kits in the chat
3./kit claim <name>- gives the items of the corresponding kit to the player

**Comment by John-Paul-R** [comment]
Base functionality of creating, removing, & claiming kits (with suggestions), per-kit permissions, and kit cooldowns currently implemented.
