### ISSUE TITLE
Compability with Simple Animated Guns

### ISSUE THREAD

**Issue by LittleLigr** [John-Paul-R/kits#10]
### Expected behavior

Minecraft server with Kits and Simple Animated Guns

### Observed/actual behavior

Hello! When launching server with Kits and [Simple Animated Guns](https://www.curseforge.com/minecraft/mc-mods/fabric-simple-animated-guns) I have such error.

### Steps/models to reproduce

Install fabric 0.14.13 server
Install Kits
Install Simple Animated Guns
Launch server

### Version

1.19.2

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

https://gist.github.com/LittleLigr/f2e55cee64e7d413d79d4ba82123d615

**Comment by LittleLigr** [comment]
Well, it's not compability issue.
I tried to start server with just Kits and fabric 0.14.14 on mc 1.19.2 and get this error:
https://gist.github.com/LittleLigr/d246f4b89d70b0051e1313a2edd12e3c

**Comment by LittleLigr** [comment]
I also tried on Fabric 0.14.11-14 with fabric api 0.(58.6, 64.0, 73.2) - throwing errors.

**Comment by John-Paul-R** [comment]
It's likely that the 1.19 version of `kits` is not compatible with mc1.19.2.

There is also a 1.19.3 version. If you can upgrade your server version, it might work.

Otherwise, I'll see what I can do later this week.

**Comment by John-Paul-R** [comment]
Actually, here is a _super_ quick attempt at a 1.19.2 build, lmk if this works for you.

https://modrinth.com/mod/kits/version/1.5.0-mc1.19.2

**Comment by LittleLigr** [comment]
> Actually, here is a _super_ quick attempt at a 1.19.2 build, lmk if this works for you.
> 
> https://modrinth.com/mod/kits/version/1.5.0-mc1.19.2

Thanks for such fast reply.
Tried 1.19.2 build
https://gist.github.com/LittleLigr/cd8a0ba4385233997d7d6e2955b0773d

**Comment by John-Paul-R** [comment]
Oops, I missed a bug. Give this a whirl: https://modrinth.com/mod/kits/version/1.5.0-v2-mc1.19.2

**Comment by LittleLigr** [comment]
> Oops, I missed a bug. Give this a whirl: https://modrinth.com/mod/kits/version/1.5.0-v2-mc1.19.2

Yes, It's work! Thank you!

**Comment by John-Paul-R** [comment]
Perfect! Thanks for the report and the logs!
