### ISSUE TITLE
Kits are broken after restart

### ISSUE THREAD

**Issue by Rusketh** [John-Paul-R/kits#27]
### Expected behavior

Kits are empty after server reboot

### Observed/actual behavior

After a server restart claiming a kit will not give you any items.

### Steps/models to reproduce

Add a kit and then restart, then claim the kit.
You will get the kit but the items will not be included in the kit.

### Version

Fabric MC 1.21.1

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by John-Paul-R** [comment]
Well that's bad. Successfully reproduced. Many thanks for the report. I'll try to have this fixed ASAP!

**Comment by arnokeesman** [comment]
Hmmm, guess I could've tested kit creation more recently, its just been the same world with existing kits for a while
Can't say this isn't my bad
Nice one on the quick fix JP

**Comment by John-Paul-R** [comment]
I missed it too (and also didn't test well enough, it seems lol).

Wrote a whole essay in the commit message about the confusing-ness of the new CODEC/Encoder types in general.

Amyway, this should be fixed on the latest version for all platforms!
