### ISSUE TITLE
GUI for available kits

### ISSUE THREAD

**Issue by Soham52** [John-Paul-R/kits#3]
Add a GUI for available kits when /kits is entered 
![SmartSelect_20210729-075122_Chrome.jpg](https://user-images.githubusercontent.com/73898737/127421556-09ce3cd7-14ca-4049-90db-7e20a5a72382.jpg)

**Comment by John-Paul-R** [comment]
Great, doable idea. I am quite busy irl over the next week or so, no eta atm. Consider it added to the list.

**Comment by Soham52** [comment]
Thanks 👍

**Comment by John-Paul-R** [comment]
Well that took a while.

Added in 67f2284, 4879aea. Will be included in next release (1.5).
