### ISSUE TITLE
Port to 1.19

### ISSUE THREAD

**Issue by CamperSamu** [John-Paul-R/kits#9]
### Is your feature request related to a problem?

The mod is not available for newer game versions and I need it to work on Minecraft 1.19

### Describe the solution or feature you'd like.

A quick port to 1.19, nothing too fancy

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported mod version.

**Comment by John-Paul-R** [comment]
Will try to have this out by the weekend

**Comment by John-Paul-R** [comment]
[Kits `1.4.2-mc1.19`](https://github.com/John-Paul-R/kits/releases/tag/1.4.2-mc1.19)
